package io.bigradar.app.bigradar


const val READ_MESSAGE_EVENT = "client/conversation/read"
const val TYPING_START_EVENT = "server/typing/start"
const val TYPING_STOP_EVENT = "server/typing/stop"
const val EMIT_TYPING_STOP_EVENT = "client/typing/stop"
const val EMIT_TYPING_START_EVENT = "client/typing/start"
const val EMIT_MESSAGE_EVENT = "client/message/send"
const val CONVERSATION_ID_KEY = "conversationId"
const val USER_ID_KEY = "user_id"
const val USER_NAME_KEY = "user_name"
const val NEW_CONVERSATION_EVENT = "new conversation"
const val NEW_MESSAGE_EVENT = "server/message/send"
const val CONNECT_EVENT = "connect"
const val ERROR_EVENT = "error"
const val BROADCAST_NEW_MESSAGE = "BROADCAST_NEW_MESSAGE"
const val BROADCAST_PROFILE_UPDATE = "BROADCAST_PROFILE_UPDATE"
const val BROADCAST_READ_CONVERSATION = "BROADCAST_READ_CONVERSATION"
const val BROADCAST_MESSAGE_KEY = "broad_cast_message"
const val CONVERSATION_USER_NAME = "CONVERSATION_USER_NAME"
const val My_NAME_DATA_KEY = "sending_my_name_data_key"
const val My_PHONE_DATA_KEY = "sending_my_phone_data_key"
const val USER_URL = "user_profile_url"
const val PROFILE_UPDATED_NAME ="PROFILE_UPDATED_NAME"
const val PROFILE_UPDATED_EMAIL ="PROFILE_UPDATED_EMAIL"
const val PROFILE_UPDATED_AVATAR ="PROFILE_UPDATED_AVATAR"
const val READ_CONVERSATION_ID = "READ_CONVERSATION_ID"
const val CHAT_ACTIVITY = "io.bigradar.app.bigradar.controllers.conversation.ChatActivity"
const val ACTIVE_USER_ID_KEY = "ACTIVE_USER_ID_KEY"
const val ACTIVE_USER_NAME_KEY = "ACTIVE_USER_NAME_KEY"
const val ACTIVE_CONVERSATION_ID_KEY = "ACTIVE_CONVERSATION_ID_KEY"
const val EMIT_MESSAGE_READ = "client/message/read"
const val EMIT_CONVERSATION_READ = "client/conversation/read"
const val MESSAGE_READ = "server/message/read"
const val CONVERSATION_READ = "server/conversation/read"
const val USER_JOIN = "server/users/join"
const val USER_LEAVE= "server/users/leave"

